version: '3'

services:
  api:
    build: .
    command: uvicorn src.app:app --host 0.0.0.0 --reload
    volumes:
      - ./src:/app/src
    ports:
      - 8000:8000
  redis:
    image: redis
    ports:
      - 6379